configuration: 
  name: qa4mre
  author: ziy
  
persistence-provider:
  inherit: persistence.local-persistence-provider

collection-reader:
  inherit: collectionreaders.CollectionReaderDescriptor

pipeline:
  # question and document annotations: data -> XMIs
  - inherit: ecd.phase
    name: TextSegmenter
    options: |
      - inherit: annotators.TextSegmenter

  - inherit: ecd.phase
    name: StanfordSentenceAnnotator
    options: |
      - inherit: annotators.StanfordSentenceAnnotator

  - inherit: ecd.phase
    name: NoiseFilter
    options: |
      - inherit: annotators.NoiseFilter

  - inherit: ecd.phase
    name: StanfordNLPAnnotator
    options: |
      - inherit: annotators.StanfordNLPAnnotator

  - inherit: ecd.phase
    name: StanfordQuestionNLPAnnotator
    options: |
      - inherit: annotators.StanfordQuestionNLPAnnotator

  - inherit: ecd.phase
    name: PhraseAnnotator
    options: |
      - inherit: annotators.PhraseAnnotator

  - inherit: ecd.phase
    name: QuestionPhraseAnnotator
    options: |
      - inherit: annotators.QuestionPhraseAnnotator

  - inherit: ecd.phase
    name: NEAnnotator
    options: |
      - inherit: annotators.NEAnnotator

  - inherit: ecd.phase
    name: QuestionNEAnnotator
    options: |
      - inherit: annotators.QuestionNEAnnotator

  - inherit: ecd.phase
    name: SynonymAnnotator
    options: |
      - inherit: annotators.SynonymAnnotator

  - inherit: ecd.phase
    name: QASynonymAnnotator
    options: |
      - inherit: annotators.QASynonymAnnotator

  - inherit: ecd.phase
    name: CasConsumer
    options: |
      - inherit: consumers.CasConsumerDescriptor

  # indexing
  - inherit: ecd.phase
    name: SolrIndexer
    options: |
      - inherit: annotators.SolrIndexer
  
  # answer ranking and merging: XMIs -> results
  - inherit: ecd.phase
    name: QuestionCandSentSimilarityMatcher
    options: |
      - inherit: annotators.QuestionCandSentSimilarityMatcher

  - inherit: ecd.phase
    name: AnswerChoiceCandAnsSimilarityScorer
    options: |
      - inherit: annotators.AnswerChoiceCandAnsSimilarityScorer

  - inherit: ecd.phase
    name: AnswerChoiceCandAnsSimilarityScorer
    options: |
      - inherit: annotators.AnswerSelectionByKCandVoting
